name: MSDO
on:
  push:
    branches:
      - main

jobs:
  sample:
    name: Microsoft Security DevOps

    # MSDO runs on windows-latest.
    # ubuntu-latest also supported
    runs-on: windows-latest

    permissions:
      contents: read
      id-token: write
      actions: read
      security-events: write

    steps:

      # Checkout your code repository to scan
      - uses: actions/checkout@v3

      # Run analyzers
      - name: Run Microsoft Security DevOps Analysis (Template Analyzer)
        uses: microsoft/security-devops-action@latest
        with:
          policy: microsoft  # Use the 'microsoft' pre-configured policy
          tools: templateanalyzer  # Specify only 'templateanalyzer' tool

      # Upload alerts to the Security tab
      - name: Upload alerts to Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}

      # Upload alerts file as a workflow artifact
      - name: Upload alerts file as a workflow artifact
        uses: actions/upload-artifact@v3
        with:
          name: alerts
          path: ${{ steps.msdo.outputs.sarifFile }}
